### ISSUE TITLE
Incorrect SARI to GND alignment resulting in URI that refers to two persons at the same time

### ISSUE THREAD

**Issue by andreghattas13** [swiss-art-research-net/bso-data-pipeline#27]
Hello,

The following URI's are not aligned well as they refer to two separate GND URL's that are supposed to represent two separate entities - 

* https://resource.swissartresearch.net/actor/1629E9CA-1554-3EAC-A27B-70FB7F4AAB40 (Füßli, Heinrich) -
    * https://d-nb.info/gnd/136012086
    * https://d-nb.info/gnd/136012019
* https://resource.swissartresearch.net/actor/583ECC0C-D4D6-3993-8595-62EB22A370D5 (Füssli, Johann Heinrich) -
    * https://d-nb.info/gnd/136012159
    * https://d-nb.info/gnd/118536745
* https://resource.swissartresearch.net/actor/EA2053E4-51E1-3D31-993F-3DC52936F9A2 (Füssli, Johann Melchior) -
    * https://d-nb.info/gnd/133989348
    * https://d-nb.info/gnd/1013908848

**Comment by fkraeutli** [comment]
Seems to be partly due to incorrect GNDs (https://github.com/swiss-art-research-net/bso-data/commit/0f5d2eef9d975e1aaffbd3ef7171e185ea154878) partly because we merged Füssli that we thought to be the same. I separated them again (https://github.com/swiss-art-research-net/bso-data-pipeline/commit/c726056d1d2966a7f60d2e7c92a5186abf61a0fd and https://github.com/swiss-art-research-net/bso-data-pipeline/commit/46714563e15fe2567969b3b2552ae27a0feea282). Pipeline is running
