### ISSUE TITLE
Im Viewer-Bild der Georeferenzierung wird die Ansicht nicht dargestellt oder nur schwarzes Bildfeld mit Kreis

### ISSUE THREAD

**Issue by michaelmatile** [swiss-art-research-net/bso-data-pipeline#36]
**Im Viewer-Bild der Georeferenzierung wird die Ansicht nicht dargestellt - nur 3D-Ansicht:**

https://bso.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477426
https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477429
https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477433
https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477435
https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477440
https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477448

**Hier zeigt das Bild nur schwarze Fläche mit weissem Kreis (kommt oft vor!):**
https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477430
https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477438
https://bso.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477446

**Mit Fehlermeldung:**
https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477432
https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477445

Vielen Dank für die Kontrolle
Michael

**Comment by fkraeutli** [comment]
Die ersten beiden Anzeigefehler scheinen mit dem sMapshot viewer zusammenzuhängen. Ich leite sie weiter. Die Fehlermeldungen schaue ich mir gerade an

**Comment by fkraeutli** [comment]
Images were not published. Published them in the sMapshot backoffice

**Comment by fkraeutli** [comment]
Fixed our issues, passed the others on to sMapshot

**Comment by fkraeutli** [comment]
Reply from Stéphane:

> Thanks for the information, I checked the links and a few were working correctly on my side: https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477429
https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477435
https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477440
https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477448
https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477430 https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477438 https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477438
 For some, the view was validated while the image was indeed not correctly displayed in the validation mode: https://bso.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477426
https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477433
 
For those one, it comes apparently from the fact that the camera position is computed in the ground. In such cases, we move the camera up to the ground level, but it may break the alignment. In most cases it is not visible since the difference is low but in the images above it fails. In those cases, if you play with the depth slider, the image would show at some point. We are working on a better fix to position the camera along the camera axis, we hope to have it live in the coming weeks. Meanwhile, probably the image should not be validated if is does not display correctly in the validation view.
 
For the comment with the black area, I am not sure I follow fully. The issue I could see is that sometimes WebGL may crash in the browser and the 3D view would not show (and other 3D website based on WebGL would not show either). In such cases, the viewer will work again after a restart of the browser.
